language: python
python:
  - "2.6"
  - "2.7"
services: mysql
install:
  - pip install -r requirements/dev.txt --use-mirrors
  - pip install coveralls
before_script:
  - mysql -e 'create database captain;'
script:
  - coverage run --source=captain manage.py test --noinput
after_success:
  - coveralls
