language: python
python:
  - "2.6"
  - "2.7"
services: mysql
install:
  - pip install -r requirements/dev.txt --use-mirrors
before_script:
  - mysql -e 'create database captain;'
script: python manage.py test --noinput
